"""
empty message

Revision ID: 3ea8c66c2506
Revises: 58436bc4c4ab
Create Date: 2012-09-30 14:01:07.026728

"""

# revision identifiers, used by Alembic.
revision = '3ea8c66c2506'
down_revision = '58436bc4c4ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('contains_keywords', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'contains_keywords')
    ### end Alembic commands ###
