"""
empty message

Revision ID: 43694797ac6f
Revises: 484e6ef51e0b
Create Date: 2012-09-30 12:50:59.274714

"""

# revision identifiers, used by Alembic.
revision = '43694797ac6f'
down_revision = '484e6ef51e0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('inserted', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'inserted')
    ### end Alembic commands ###
