"""
empty message

Revision ID: 58436bc4c4ab
Revises: 43694797ac6f
Create Date: 2012-09-30 13:57:08.650449

"""

# revision identifiers, used by Alembic.
revision = '58436bc4c4ab'
down_revision = '43694797ac6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
